"""added verified column to casino model

Revision ID: 48ca3f66e535
Revises: 0d8c8e00f2cb
Create Date: 2022-12-05 13:13:08.097332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ca3f66e535'
down_revision = '0d8c8e00f2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casino', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casino', 'verified')
    # ### end Alembic commands ###
